inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3
  Exclude:
    - 'tasks/release/**/*'

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'features/*'
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Security/Eval:
  Exclude:
    - 'features/**/*'

Style/Attr:
  Exclude:
    - 'lib/aws-record/record/attributes.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false