# frozen_string_literal: true

require 'aws-sdk-dynamodb'
require_relative 'aws-record/record/client_configuration'
require_relative 'aws-record/record'
require_relative 'aws-record/record/attribute'
require_relative 'aws-record/record/attributes'
require_relative 'aws-record/record/dirty_tracking'
require_relative 'aws-record/record/errors'
require_relative 'aws-record/record/item_collection'
require_relative 'aws-record/record/item_data'
require_relative 'aws-record/record/item_operations'
require_relative 'aws-record/record/key_attributes'
require_relative 'aws-record/record/model_attributes'
require_relative 'aws-record/record/query'
require_relative 'aws-record/record/secondary_indexes'
require_relative 'aws-record/record/table_config'
require_relative 'aws-record/record/table_migration'
require_relative 'aws-record/record/version'
require_relative 'aws-record/record/transactions'
require_relative 'aws-record/record/buildable_search'
require_relative 'aws-record/record/batch_read'
require_relative 'aws-record/record/batch_write'
require_relative 'aws-record/record/batch'
require_relative 'aws-record/record/marshalers/string_marshaler'
require_relative 'aws-record/record/marshalers/boolean_marshaler'
require_relative 'aws-record/record/marshalers/integer_marshaler'
require_relative 'aws-record/record/marshalers/float_marshaler'
require_relative 'aws-record/record/marshalers/date_marshaler'
require_relative 'aws-record/record/marshalers/date_time_marshaler'
require_relative 'aws-record/record/marshalers/time_marshaler'
require_relative 'aws-record/record/marshalers/epoch_time_marshaler'
require_relative 'aws-record/record/marshalers/list_marshaler'
require_relative 'aws-record/record/marshalers/map_marshaler'
require_relative 'aws-record/record/marshalers/string_set_marshaler'
require_relative 'aws-record/record/marshalers/numeric_set_marshaler'

module Aws
  module Record
  end
end
